### ISSUE TITLE
Banners don't pull for Sickbeard under Trakt branch

### ISSUE THREAD

**Issue by antoinesylvia** [ebright/maraschino#13]
![sickbeard](https://cloud.githubusercontent.com/assets/2508410/12261824/419afaa4-b8e9-11e5-9e54-9f5e86dea5a9.png)
Show banners work for all of the other branches except Trakt under the sickbeard module, still functions in compact mode. Thanks for getting Trakt up and running.

**Comment by ebright** [comment]
@antoinesylvia 
Thanks for the report.  It looks like the local cache folder was changed from sickbeard to sickrage by the sickrage updates.  I just updated the folder path
