### ISSUE TITLE
Add Ability to support both Kodi AND plex as opposed to just one or the other.

### ISSUE THREAD

**Issue by famewolf** [ebright/maraschino#15]
Currently the user has the choice to use the main branch and get XBMC support or your branch and get plex support.  Ideally the user could use both.  For example I run mediaportal (a spinoff of xbmc) on my main tv but my server runs plex to feed the picture to tv's in other parts of the house via android tv sticks.

**Comment by ebright** [comment]
@famewolf 

 I believe that Roostay is the one who created the Plex fork.  He would be the best one to ask about adding an option to support both.
